### ISSUE TITLE
No '1.0' version for InfernoJS

### ISSUE THREAD

**Issue by cuibonobo** [localvoid/uibench#3]
From looking at the InfernoJS UI Benchmark repo (https://github.com/infernojs/uibench-inferno), it seems like only '0.7' and 'dev' are available.

**Comment by localvoid** [comment]
It is uploaded in the `docs` directory, https://github.com/infernojs/uibench-inferno/tree/master/docs/1.0

Waiting for a change in the repo settings, so it will serve from `docs` directory instead of `gh-pages` branch.
